version: 2

updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    assignees:
      - "AndrewFlan"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"

  # Keep Terraform providers up to date
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    assignees:
      - "AndrewFlan"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
