name: Terraform

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

# Required for OIDC
permissions:
    id-token: write
    contents: read
    pull-requests: write

jobs:
    terraform:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Configure AWS credentials via OIDC
              uses: aws-actions/configure-aws-credentials@v6
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: us-east-1
                  audience: sts.amazonaws.com

            - name: Install Terraform
              uses: hashicorp/setup-terraform@v4
              with:
                  terraform_version: "1.15.0"

            - name: Terraform Init
              run: terraform init

            - name: Terraform Plan
              run: |
                  set -o pipefail
                  terraform plan -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" -var="domain_name=andrewflanigan.com" -out=tfplan 2>&1 | tee plan_output.txt

            - name: Comment plan on PR
              if: github.event_name== 'pull_request'
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  PLAN=$(cat plan_output.txt)
                  MARKER="<!-- terraform-plan -->"

                  # Find existing comment ID if it exists
                  COMMENT_ID=$(gh api \
                    repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
                    --jq ".[] | select(.body | startswith(\"$MARKER\")) | .id" | head -1)

                  BODY="$MARKER
                  ## Terraform Plan
                  \`\`\`hcl
                  $PLAN
                  \`\`\`"

                  if [ -n "$COMMENT_ID" ]; then
                      # Update existing comment
                      gh api \
                      repos/${{ github.repository }}/issues/comments/$COMMENT_ID \
                      -X PATCH \
                      -f body="$BODY"
                  else
                      # Create new comment
                      gh pr comment ${{ github.event.pull_request.number }} --body "$BODY"
                  fi

            # Only apply on push to main, not on pull requests
            - name: Terraform Apply
              if: github.ref == 'refs/heads/main' && github.event_name == 'push'
              run: terraform apply -auto-approve tfplan

            - name: Update EC2 instance ID secret
              if: github.ref == 'refs/heads/main' && github.event_name == 'push'
              env:
                  GH_TOKEN: ${{ secrets.GH_PAT }}
              run: |
                  INSTANCE_ID=$(terraform output -raw instance_id)
                  gh secret set EC2_INSTANCE_ID \
                    --repo AndrewFlan/my-website \
                    --body "$INSTANCE_ID"
